### ISSUE TITLE
support for css classes

### ISSUE THREAD

**Issue by mattkrick** [domchristie/humps#18]
it'd be a neat feature to correctly camelize/decamelize css classes. Since prefixes follow their own rule, it'd require something special like:
```
function camelCaseCSS(string) {
  if (string.indexOf("-ms-") === 0) {
    string = string.substr(1);
  }
  return string.replace(/-(\w|$)/g, (_, char) => char.toUpperCase());
}
```
Maybe have an `isCSS` options prop for the API? It could detect css automatically & use this function, but that's seems a little too magical.

**Comment by vitaly-t** [comment]
Could you, please, provide one example of why somebody would want to camelize CSS?

**Comment by mattkrick** [comment]
CSS mutations within JavaScript must use camel case, whether it's jquery or
react or anything in between. A second case is directly reading from the
document.stylesheets

**Comment by vitaly-t** [comment]
In all cases that I know about one uses camelize as a uni-directional operation, i.e. a source is transformed for ease of further consumption.

With CSS however, the source is a stylesheet which defines reusable styles. If a client changes any CSS class name, it won't be usable within the client anymore, i.e. you would have to transform both the source CSS entirely, and all the client instances of where it is being used. I don't know how practical this can really be...
