### ISSUE TITLE
Changelog for 2.0.0 missing

### ISSUE THREAD

**Issue by readme42** [domchristie/humps#32]
Sadly the Changelog for the new Release 2.0.0 is missing. 

My main question is: Is there any breaking change when upgrading from 1.1.0 to 2.0.0?

**Comment by domchristie** [comment]
The only change is https://github.com/domchristie/humps/commit/49678e68dbf7cf70fb168b12e026a633066ce04f i.e. functions do not get converted to empty objects. I will add this to the release notes.

Although it is only a minor change, it still changes the behaviour of the conversion function. Hope that helps.

**Comment by harriha** [comment]
Hi, 

Seems that the Changelog file isn't updated - would be great to have that up-to-date, makes updating the library more straightforward (although this time there wasn't that much changes).
