### ISSUE TITLE
Option to not camelize all-caps CONSTANTS

### ISSUE THREAD

**Issue by pistachiomatt** [domchristie/humps#34]
When I bootstrap data into my app, the constants are named `ENV` and `PUSHER_KEY` but running `camelizeKeys` changes them to `eNV` and `pUSHERKEY`. Probably never intended, but an option to skip over constants would be lovely.

**Comment by domchristie** [comment]
Hi @pistachiomatt 

This is possible by altering the conversation behaviour, as detailed here: https://github.com/domchristie/humps#converting-object-keys

You could do something like:

```js
humps.camelizeKeys(obj, function (key, convert) {
  return /^[A-Z0-9_]+$/.test(key) ? key : convert(key);
});
```
