### ISSUE TITLE
string.replace is not a function

### ISSUE THREAD

**Issue by droganov** [domchristie/humps#37]
I get this exception on attempt to camelize google geocoder response with v2:

`camelize(payload)` results in:

![image](https://cloud.githubusercontent.com/assets/1375299/24331593/02fb75c4-1240-11e7-9fce-2a7c78b01c89.png)

**Comment by droganov** [comment]
Please ignore, I had to use `camelizeKeys`

**Comment by conroywhitney** [comment]
Still was helpful to find this here. Thanks!
