### ISSUE TITLE
decamelizeKeys fails in chrome 51

### ISSUE THREAD

**Issue by bdwain** [domchristie/humps#38]
I'm not totally sure if this is a bug in chrome 51 or in this library, but in chrome 52, i get this result

window.humps.decamelizeKeys({fooBar: 123})
Object {foo_bar: 123}

and in chrome 51, i get this

window.humps.decamelizeKeys({fooBar: 123})
Object {foobar: 123}

chrome 50 seems fine so it's just 51

**Comment by bdwain** [comment]
i actually think this is something else related to my setup. sorry for the confusion.

**Comment by IcyFermion** [comment]
I've encountered the same issue, wonder how you fixed if?

**Comment by bdwain** [comment]
@IcyFermion assuming you are running into the same issue, it was addressed here https://github.com/mishoo/UglifyJS2/issues/1964

the latest version of uglifyjs should fix it. if not, you need to turn off the reduce_vars option
