### ISSUE TITLE
Conversion of screaming snake case to camel case

### ISSUE THREAD

**Issue by jreut** [domchristie/humps#40]
I was surprised by the behavior of converting a screaming snake case string to camel case.

Currently,

```js
const camelize = require('humps').camelize
camelize('HELLO_WORLD') === 'hELLOWORLD'
```

whereas I expected it to be more like

```js
camelize('HELLO_WORLD') === 'helloWorld'
```

Which (if any) is the intended behavior?

**Comment by codepunkt** [comment]
I'm having the exact same problem at the moment.

```javascript
const { camelize } = require('humps')
camelize('GITISF2REQ') === 'gITISF2REQ' // true, unexpected
camelize('GITISF2REQ') === 'gitisf2req' // false, but what i expected
```

**Comment by jreut** [comment]
It seems this project is inactive, so I'm going to close this issue.
