### ISSUE TITLE
Decamelizing uppercase keys

### ISSUE THREAD

**Issue by lucapasquale** [domchristie/humps#42]
I'm having a problem decamelizing keys that are all uppercase, here is what's happening:

```
const options = { URL: 'www.google.com' };

decamelizeKeys(options);
```

is returning `{ u_r_l: (...) }`, instead of just ignoring that key

**Comment by cemremengu** [comment]
Exactly, it should check if the key starts with a lowercase letter

**Comment by ajay-gandhi** [comment]
@cemremengu without arguable minor changes to the source, this solution won't work. `depascalize` is an alias for `decamelize`, and `depascalize` shouldn't ignore a key such as "HelloWorldFooBar".
