### ISSUE TITLE
Cannot split on numbers properly with the readme example

### ISSUE THREAD

**Issue by adesurirey** [domchristie/humps#59]
When dealing with 1 digit numbers the readme example is ok 
```
humps.decamelize('helloWorld1', { split: /(?=[A-Z0-9])/ }) // 'hello_world_1'
```

But for 1+ digit numbers it does not produce the expected result
```
humps.decamelize('helloWorld12', { split: /(?=[A-Z0-9])/ }) // 'hello_world_1_2'
```

I am unsure that we could solve this issue only using `split` option. 

Best I could do: 
```
humps.decamelize('helloWorld12', { split: /(?=[A-Z])|[^0-9](?=[0-9])/ }) // 'hello_worl_12'
```

**Comment by adesurirey** [comment]
working well with this regex
```
/(?=[A-Z])|(?<=[a-z])(?=\d)/g
```

**Comment by jaugustodafranca** [comment]
Hey @adesurirey, I noticed that this approach doesn't will be supported on Safari (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility)

![Screen Shot 2021-09-13 at 14 42 03](https://user-images.githubusercontent.com/38357905/133131266-0824ee6f-6e0f-4045-8b76-f709891baefd.png)

I'm trying to find a compatible regex, if I find an answer I will post it here too.
